[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [".", "app"]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v -p no:warnings"
